<?php

namespace SiteBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBooksByCategory($category) {

        $qb = $this->createQueryBuilder('b')->join('b.categories', 'c');
        $qb->where($qb->expr()->in('c.id', array($category)));
        $qb->groupBy('b.id');
        $qb->orderBy('b.sort', 'asc');

        return $qb->getQuery()
            ->getResult();
    }
}
