<?php

namespace SiteBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesIndexById () {

        $qb = $this->createQueryBuilder('c');
        $qb->indexBy('c', 'c.id');

        return $qb->getQuery()
            ->getResult();
    }
}
